/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as IeltsPreparationRouteImport } from './routes/ielts-preparation'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyNowRouteImport } from './routes/apply-now'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsPreparationRoute = IeltsPreparationRouteImport.update({
  id: '/ielts-preparation',
  path: '/ielts-preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyNowRoute = ApplyNowRouteImport.update({
  id: '/apply-now',
  path: '/apply-now',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/ielts-preparation': typeof IeltsPreparationRoute
  '/services': typeof ServicesRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/ielts-preparation': typeof IeltsPreparationRoute
  '/services': typeof ServicesRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/ielts-preparation': typeof IeltsPreparationRoute
  '/services': typeof ServicesRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply-now'
    | '/contact'
    | '/destinations'
    | '/ielts-preparation'
    | '/services'
    | '/success-stories'
    | '/universities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply-now'
    | '/contact'
    | '/destinations'
    | '/ielts-preparation'
    | '/services'
    | '/success-stories'
    | '/universities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply-now'
    | '/contact'
    | '/destinations'
    | '/ielts-preparation'
    | '/services'
    | '/success-stories'
    | '/universities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyNowRoute: typeof ApplyNowRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  IeltsPreparationRoute: typeof IeltsPreparationRoute
  ServicesRoute: typeof ServicesRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  UniversitiesRoute: typeof UniversitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts-preparation': {
      id: '/ielts-preparation'
      path: '/ielts-preparation'
      fullPath: '/ielts-preparation'
      preLoaderRoute: typeof IeltsPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-now': {
      id: '/apply-now'
      path: '/apply-now'
      fullPath: '/apply-now'
      preLoaderRoute: typeof ApplyNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyNowRoute: ApplyNowRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  IeltsPreparationRoute: IeltsPreparationRoute,
  ServicesRoute: ServicesRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  UniversitiesRoute: UniversitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
