/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as VisaAssistanceRouteImport } from './routes/visa-assistance'
import { Route as UniversityApplicationsRouteImport } from './routes/university-applications'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as StudyInUsaRouteImport } from './routes/study-in-usa'
import { Route as StudyInUkRouteImport } from './routes/study-in-uk'
import { Route as StudyInNewZealandRouteImport } from './routes/study-in-new-zealand'
import { Route as StudyInIrelandRouteImport } from './routes/study-in-ireland'
import { Route as StudyInGermanyRouteImport } from './routes/study-in-germany'
import { Route as StudyInFranceRouteImport } from './routes/study-in-france'
import { Route as StudyInCanadaRouteImport } from './routes/study-in-canada'
import { Route as StudyInAustraliaRouteImport } from './routes/study-in-australia'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ScholarshipGuidanceRouteImport } from './routes/scholarship-guidance'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PreDepartureBriefingRouteImport } from './routes/pre-departure-briefing'
import { Route as PostArrivalSupportRouteImport } from './routes/post-arrival-support'
import { Route as MissionVisionRouteImport } from './routes/mission-vision'
import { Route as InnovatorFounderVisaRouteImport } from './routes/innovator-founder-visa'
import { Route as IeltsPreparationRouteImport } from './routes/ielts-preparation'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApplyNowRouteImport } from './routes/apply-now'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisaAssistanceVisaKeyRouteImport } from './routes/visa-assistance_.$visaKey'
import { Route as BlogBlogIdRouteImport } from './routes/blog_.$blogId'

const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaAssistanceRoute = VisaAssistanceRouteImport.update({
  id: '/visa-assistance',
  path: '/visa-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityApplicationsRoute = UniversityApplicationsRouteImport.update({
  id: '/university-applications',
  path: '/university-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyInUsaRoute = StudyInUsaRouteImport.update({
  id: '/study-in-usa',
  path: '/study-in-usa',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyInUkRoute = StudyInUkRouteImport.update({
  id: '/study-in-uk',
  path: '/study-in-uk',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyInNewZealandRoute = StudyInNewZealandRouteImport.update({
  id: '/study-in-new-zealand',
  path: '/study-in-new-zealand',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyInIrelandRoute = StudyInIrelandRouteImport.update({
  id: '/study-in-ireland',
  path: '/study-in-ireland',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyInGermanyRoute = StudyInGermanyRouteImport.update({
  id: '/study-in-germany',
  path: '/study-in-germany',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyInFranceRoute = StudyInFranceRouteImport.update({
  id: '/study-in-france',
  path: '/study-in-france',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyInCanadaRoute = StudyInCanadaRouteImport.update({
  id: '/study-in-canada',
  path: '/study-in-canada',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyInAustraliaRoute = StudyInAustraliaRouteImport.update({
  id: '/study-in-australia',
  path: '/study-in-australia',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipGuidanceRoute = ScholarshipGuidanceRouteImport.update({
  id: '/scholarship-guidance',
  path: '/scholarship-guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreDepartureBriefingRoute = PreDepartureBriefingRouteImport.update({
  id: '/pre-departure-briefing',
  path: '/pre-departure-briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const PostArrivalSupportRoute = PostArrivalSupportRouteImport.update({
  id: '/post-arrival-support',
  path: '/post-arrival-support',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionVisionRoute = MissionVisionRouteImport.update({
  id: '/mission-vision',
  path: '/mission-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovatorFounderVisaRoute = InnovatorFounderVisaRouteImport.update({
  id: '/innovator-founder-visa',
  path: '/innovator-founder-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsPreparationRoute = IeltsPreparationRouteImport.update({
  id: '/ielts-preparation',
  path: '/ielts-preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyNowRoute = ApplyNowRouteImport.update({
  id: '/apply-now',
  path: '/apply-now',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaAssistanceVisaKeyRoute = VisaAssistanceVisaKeyRouteImport.update({
  id: '/visa-assistance_/$visaKey',
  path: '/visa-assistance/$visaKey',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlogIdRoute = BlogBlogIdRouteImport.update({
  id: '/blog_/$blogId',
  path: '/blog/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply-now': typeof ApplyNowRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/ielts-preparation': typeof IeltsPreparationRoute
  '/innovator-founder-visa': typeof InnovatorFounderVisaRoute
  '/mission-vision': typeof MissionVisionRoute
  '/post-arrival-support': typeof PostArrivalSupportRoute
  '/pre-departure-briefing': typeof PreDepartureBriefingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/scholarship-guidance': typeof ScholarshipGuidanceRoute
  '/services': typeof ServicesRoute
  '/study-in-australia': typeof StudyInAustraliaRoute
  '/study-in-canada': typeof StudyInCanadaRoute
  '/study-in-france': typeof StudyInFranceRoute
  '/study-in-germany': typeof StudyInGermanyRoute
  '/study-in-ireland': typeof StudyInIrelandRoute
  '/study-in-new-zealand': typeof StudyInNewZealandRoute
  '/study-in-uk': typeof StudyInUkRoute
  '/study-in-usa': typeof StudyInUsaRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
  '/university-applications': typeof UniversityApplicationsRoute
  '/visa-assistance': typeof VisaAssistanceRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/visa-assistance/$visaKey': typeof VisaAssistanceVisaKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply-now': typeof ApplyNowRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/ielts-preparation': typeof IeltsPreparationRoute
  '/innovator-founder-visa': typeof InnovatorFounderVisaRoute
  '/mission-vision': typeof MissionVisionRoute
  '/post-arrival-support': typeof PostArrivalSupportRoute
  '/pre-departure-briefing': typeof PreDepartureBriefingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/scholarship-guidance': typeof ScholarshipGuidanceRoute
  '/services': typeof ServicesRoute
  '/study-in-australia': typeof StudyInAustraliaRoute
  '/study-in-canada': typeof StudyInCanadaRoute
  '/study-in-france': typeof StudyInFranceRoute
  '/study-in-germany': typeof StudyInGermanyRoute
  '/study-in-ireland': typeof StudyInIrelandRoute
  '/study-in-new-zealand': typeof StudyInNewZealandRoute
  '/study-in-uk': typeof StudyInUkRoute
  '/study-in-usa': typeof StudyInUsaRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
  '/university-applications': typeof UniversityApplicationsRoute
  '/visa-assistance': typeof VisaAssistanceRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/visa-assistance/$visaKey': typeof VisaAssistanceVisaKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply-now': typeof ApplyNowRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/ielts-preparation': typeof IeltsPreparationRoute
  '/innovator-founder-visa': typeof InnovatorFounderVisaRoute
  '/mission-vision': typeof MissionVisionRoute
  '/post-arrival-support': typeof PostArrivalSupportRoute
  '/pre-departure-briefing': typeof PreDepartureBriefingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/scholarship-guidance': typeof ScholarshipGuidanceRoute
  '/services': typeof ServicesRoute
  '/study-in-australia': typeof StudyInAustraliaRoute
  '/study-in-canada': typeof StudyInCanadaRoute
  '/study-in-france': typeof StudyInFranceRoute
  '/study-in-germany': typeof StudyInGermanyRoute
  '/study-in-ireland': typeof StudyInIrelandRoute
  '/study-in-new-zealand': typeof StudyInNewZealandRoute
  '/study-in-uk': typeof StudyInUkRoute
  '/study-in-usa': typeof StudyInUsaRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
  '/university-applications': typeof UniversityApplicationsRoute
  '/visa-assistance': typeof VisaAssistanceRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/blog_/$blogId': typeof BlogBlogIdRoute
  '/visa-assistance_/$visaKey': typeof VisaAssistanceVisaKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply-now'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/ielts-preparation'
    | '/innovator-founder-visa'
    | '/mission-vision'
    | '/post-arrival-support'
    | '/pre-departure-briefing'
    | '/privacy-policy'
    | '/scholarship-guidance'
    | '/services'
    | '/study-in-australia'
    | '/study-in-canada'
    | '/study-in-france'
    | '/study-in-germany'
    | '/study-in-ireland'
    | '/study-in-new-zealand'
    | '/study-in-uk'
    | '/study-in-usa'
    | '/success-stories'
    | '/universities'
    | '/university-applications'
    | '/visa-assistance'
    | '/why-choose-us'
    | '/blog/$blogId'
    | '/visa-assistance/$visaKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply-now'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/ielts-preparation'
    | '/innovator-founder-visa'
    | '/mission-vision'
    | '/post-arrival-support'
    | '/pre-departure-briefing'
    | '/privacy-policy'
    | '/scholarship-guidance'
    | '/services'
    | '/study-in-australia'
    | '/study-in-canada'
    | '/study-in-france'
    | '/study-in-germany'
    | '/study-in-ireland'
    | '/study-in-new-zealand'
    | '/study-in-uk'
    | '/study-in-usa'
    | '/success-stories'
    | '/universities'
    | '/university-applications'
    | '/visa-assistance'
    | '/why-choose-us'
    | '/blog/$blogId'
    | '/visa-assistance/$visaKey'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply-now'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/ielts-preparation'
    | '/innovator-founder-visa'
    | '/mission-vision'
    | '/post-arrival-support'
    | '/pre-departure-briefing'
    | '/privacy-policy'
    | '/scholarship-guidance'
    | '/services'
    | '/study-in-australia'
    | '/study-in-canada'
    | '/study-in-france'
    | '/study-in-germany'
    | '/study-in-ireland'
    | '/study-in-new-zealand'
    | '/study-in-uk'
    | '/study-in-usa'
    | '/success-stories'
    | '/universities'
    | '/university-applications'
    | '/visa-assistance'
    | '/why-choose-us'
    | '/blog_/$blogId'
    | '/visa-assistance_/$visaKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyNowRoute: typeof ApplyNowRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  FaqRoute: typeof FaqRoute
  IeltsPreparationRoute: typeof IeltsPreparationRoute
  InnovatorFounderVisaRoute: typeof InnovatorFounderVisaRoute
  MissionVisionRoute: typeof MissionVisionRoute
  PostArrivalSupportRoute: typeof PostArrivalSupportRoute
  PreDepartureBriefingRoute: typeof PreDepartureBriefingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ScholarshipGuidanceRoute: typeof ScholarshipGuidanceRoute
  ServicesRoute: typeof ServicesRoute
  StudyInAustraliaRoute: typeof StudyInAustraliaRoute
  StudyInCanadaRoute: typeof StudyInCanadaRoute
  StudyInFranceRoute: typeof StudyInFranceRoute
  StudyInGermanyRoute: typeof StudyInGermanyRoute
  StudyInIrelandRoute: typeof StudyInIrelandRoute
  StudyInNewZealandRoute: typeof StudyInNewZealandRoute
  StudyInUkRoute: typeof StudyInUkRoute
  StudyInUsaRoute: typeof StudyInUsaRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  UniversitiesRoute: typeof UniversitiesRoute
  UniversityApplicationsRoute: typeof UniversityApplicationsRoute
  VisaAssistanceRoute: typeof VisaAssistanceRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
  BlogBlogIdRoute: typeof BlogBlogIdRoute
  VisaAssistanceVisaKeyRoute: typeof VisaAssistanceVisaKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa-assistance': {
      id: '/visa-assistance'
      path: '/visa-assistance'
      fullPath: '/visa-assistance'
      preLoaderRoute: typeof VisaAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university-applications': {
      id: '/university-applications'
      path: '/university-applications'
      fullPath: '/university-applications'
      preLoaderRoute: typeof UniversityApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-in-usa': {
      id: '/study-in-usa'
      path: '/study-in-usa'
      fullPath: '/study-in-usa'
      preLoaderRoute: typeof StudyInUsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-in-uk': {
      id: '/study-in-uk'
      path: '/study-in-uk'
      fullPath: '/study-in-uk'
      preLoaderRoute: typeof StudyInUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-in-new-zealand': {
      id: '/study-in-new-zealand'
      path: '/study-in-new-zealand'
      fullPath: '/study-in-new-zealand'
      preLoaderRoute: typeof StudyInNewZealandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-in-ireland': {
      id: '/study-in-ireland'
      path: '/study-in-ireland'
      fullPath: '/study-in-ireland'
      preLoaderRoute: typeof StudyInIrelandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-in-germany': {
      id: '/study-in-germany'
      path: '/study-in-germany'
      fullPath: '/study-in-germany'
      preLoaderRoute: typeof StudyInGermanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-in-france': {
      id: '/study-in-france'
      path: '/study-in-france'
      fullPath: '/study-in-france'
      preLoaderRoute: typeof StudyInFranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-in-canada': {
      id: '/study-in-canada'
      path: '/study-in-canada'
      fullPath: '/study-in-canada'
      preLoaderRoute: typeof StudyInCanadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-in-australia': {
      id: '/study-in-australia'
      path: '/study-in-australia'
      fullPath: '/study-in-australia'
      preLoaderRoute: typeof StudyInAustraliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship-guidance': {
      id: '/scholarship-guidance'
      path: '/scholarship-guidance'
      fullPath: '/scholarship-guidance'
      preLoaderRoute: typeof ScholarshipGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-departure-briefing': {
      id: '/pre-departure-briefing'
      path: '/pre-departure-briefing'
      fullPath: '/pre-departure-briefing'
      preLoaderRoute: typeof PreDepartureBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-arrival-support': {
      id: '/post-arrival-support'
      path: '/post-arrival-support'
      fullPath: '/post-arrival-support'
      preLoaderRoute: typeof PostArrivalSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-vision': {
      id: '/mission-vision'
      path: '/mission-vision'
      fullPath: '/mission-vision'
      preLoaderRoute: typeof MissionVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovator-founder-visa': {
      id: '/innovator-founder-visa'
      path: '/innovator-founder-visa'
      fullPath: '/innovator-founder-visa'
      preLoaderRoute: typeof InnovatorFounderVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts-preparation': {
      id: '/ielts-preparation'
      path: '/ielts-preparation'
      fullPath: '/ielts-preparation'
      preLoaderRoute: typeof IeltsPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-now': {
      id: '/apply-now'
      path: '/apply-now'
      fullPath: '/apply-now'
      preLoaderRoute: typeof ApplyNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa-assistance_/$visaKey': {
      id: '/visa-assistance_/$visaKey'
      path: '/visa-assistance/$visaKey'
      fullPath: '/visa-assistance/$visaKey'
      preLoaderRoute: typeof VisaAssistanceVisaKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$blogId': {
      id: '/blog_/$blogId'
      path: '/blog/$blogId'
      fullPath: '/blog/$blogId'
      preLoaderRoute: typeof BlogBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyNowRoute: ApplyNowRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  FaqRoute: FaqRoute,
  IeltsPreparationRoute: IeltsPreparationRoute,
  InnovatorFounderVisaRoute: InnovatorFounderVisaRoute,
  MissionVisionRoute: MissionVisionRoute,
  PostArrivalSupportRoute: PostArrivalSupportRoute,
  PreDepartureBriefingRoute: PreDepartureBriefingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ScholarshipGuidanceRoute: ScholarshipGuidanceRoute,
  ServicesRoute: ServicesRoute,
  StudyInAustraliaRoute: StudyInAustraliaRoute,
  StudyInCanadaRoute: StudyInCanadaRoute,
  StudyInFranceRoute: StudyInFranceRoute,
  StudyInGermanyRoute: StudyInGermanyRoute,
  StudyInIrelandRoute: StudyInIrelandRoute,
  StudyInNewZealandRoute: StudyInNewZealandRoute,
  StudyInUkRoute: StudyInUkRoute,
  StudyInUsaRoute: StudyInUsaRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  UniversitiesRoute: UniversitiesRoute,
  UniversityApplicationsRoute: UniversityApplicationsRoute,
  VisaAssistanceRoute: VisaAssistanceRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
  BlogBlogIdRoute: BlogBlogIdRoute,
  VisaAssistanceVisaKeyRoute: VisaAssistanceVisaKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
